### PR TITLE
Feat/helm separate deployments

### PR DESCRIPTION
**Pull request by edrichhans**

### CODE REVIEW

**Comment by fredsted** [comment]
Hi, thanks for this. One thing - I think you should remove the kubernetes folder with this. :-)

**Comment by mowies** [comment]
Documentation is still pointing to the kubernetes folder and doesn't mention a helm chart at all

**Comment by mowies** [comment]
I don't even know what this is about. The PR doesn't have a description and there's no issue attached either...

**Comment by fredsted** [comment]
@mowies Looks like you meant the docs site (?) I've made an update there so it links to the helm folder.

**Comment by mowies** [comment]
thanks!
with this change, it still got a bit harder to install the tool directly from the repo, since helm can't just fetch the folder and use the chart there. it either needs a hosted chart repo or a .tgz archive that contains the chart

**Pull request merged**
